#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Default settings used by the vagrant SOC/CLM VM setup process.
---

_proxy_mounts: "{{ hostvars[deployer_node]['ansible_mounts'] |
                   selectattr('mount', 'equalto',
                              cloud.deployer.caching_proxy.fs.mount) |
                   list }}"

_clm_flavour: "{{ cloud.config.hos_mode | bool | ternary('hos8', 'soc8') }}"
_clm_version: "{{ ((cloud_version | int) == 9) | ternary('soc9', _clm_flavour) }}"

clmsetup:
  caching_proxy:
    enabled: "{{ _proxy_mounts | count | bool }}"
    mounts: "{{ _proxy_mounts }}"
  server:
    base: "{{ PACKAGE_CONSTANTS.REPO_DIR }}"
  distros:
    sles:
      dir: "ardana/sles12/zypper"
    rhel:
      dir: "ardana/rhel7/yum"
  isos:
    - dev: /dev/sr0
      path: "OS"
      name: "{{ sles.artifacts.iso.os.name }}"
      alias: "{{ sles.artifacts.iso.os.alias }}"
      iso_link: "{{ sles.artifacts.iso.os.link }}"
      distro: sles
      enabled: true
    - dev: /dev/sr1
      path: "C{{ cloud_version }}"
      name: "C{{ cloud_version }}{{ cloud.config.iso_milestone[cloud_version] }}"
      alias: "{{ cloud.artifacts.iso[_clm_version].media1.alias }}"
      iso_link: "{{ cloud.artifacts.iso[_clm_version].media1.link }}"
      enabled: true
      distro: sles
    - dev: /dev/sr2
      path: "OS"
      name: "{{ rhel.artifacts.iso.os.name }}"
      alias: "{{ rhel.artifacts.iso.os.alias }}"
      gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
      iso_link: "{{ rhel.artifacts.iso.os.link }}"
      distro: rhel
      enabled: true
  repos:
    #
    # rsync mirror based repos
    #

    # SLES12 SP3 Repos
    - mirror: "{{ clouddata_repo.mirrors_dir }}/{{ sles.artifacts.repos.sles12sp3.updates.name }}"
      path: "{{ sles.artifacts.repos.sles12sp3.updates.alias }}"
      name: "{{ sles.artifacts.repos.sles12sp3.updates.name }}"
      alias: "{{ sles.artifacts.repos.sles12sp3.updates.alias }}"
      distro: sles
      enabled: "{{ (sles.artifacts.repos.sles12sp3.updates.enabled | bool) and
                   ('updates' in sles.config.enabled_repos) }}"
    - mirror: "{{ clouddata_repo.mirrors_dir }}/{{ sles.artifacts.repos.sles12sp3.pool.name }}"
      path: "{{ sles.artifacts.repos.sles12sp3.pool.alias }}"
      name: "{{ sles.artifacts.repos.sles12sp3.pool.name }}"
      alias: "{{ sles.artifacts.repos.sles12sp3.pool.alias }}"
      distro: sles
      enabled: "{{ (sles.artifacts.repos.sles12sp3.pool.enabled | bool) and
                   ('pool' in sles.config.enabled_repos) }}"

    # SUSE OpenStack Cloud 9 Repos
    - mirror: "{{ clouddata_repo.mirrors_dir }}/{{ cloud.artifacts.repos.soc9.staging.name }}"
      path: "{{ cloud.artifacts.repos.soc9.staging.alias }}"
      name: "{{ cloud.artifacts.repos.soc9.staging.name }}"
      alias: "{{ cloud.artifacts.repos.soc9.staging.alias }}"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc9.staging.enabled | bool) and
                   ('staging' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc9') }}"
    - mirror: "{{ clouddata_repo.mirrors_dir }}/{{ cloud.artifacts.repos.soc9.devel.name }}"
      path: "{{ cloud.artifacts.repos.soc9.devel.alias }}"
      name: "{{ cloud.artifacts.repos.soc9.devel.name }}"
      alias: "{{ cloud.artifacts.repos.soc9.devel.alias }}"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc9.devel.enabled | bool) and
                   ('devel' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc9') }}"
    - mirror: "{{ clouddata_repo.mirrors_dir }}/{{ cloud.artifacts.repos.soc9.updates.name }}"
      path: "{{ cloud.artifacts.repos.soc9.updates.alias }}"
      name: "{{ cloud.artifacts.repos.soc9.updates.name }}"
      alias: "{{ cloud.artifacts.repos.soc9.updates.alias }}"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc9.updates.enabled | bool) and
                   ('updates' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc9') }}"
    - mirror: "{{ clouddata_repo.mirrors_dir }}/{{ cloud.artifacts.repos.soc9.pool.name }}"
      path: "{{ cloud.artifacts.repos.soc9.pool.alias }}"
      name: "{{ cloud.artifacts.repos.soc9.pool.name }}"
      alias: "{{ cloud.artifacts.repos.soc9.pool.alias }}"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc9.pool.enabled | bool) and
                   ('pool' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc9') }}"

    # SUSE OpenStack Cloud 8 Repos
    - mirror: "{{ clouddata_repo.mirrors_dir }}/{{ cloud.artifacts.repos.soc8.staging.name }}"
      path: "{{ cloud.artifacts.repos.soc8.staging.alias }}"
      name: "{{ cloud.artifacts.repos.soc8.staging.name }}"
      alias: "{{ cloud.artifacts.repos.soc8.staging.alias }}"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc8.staging.enabled | bool) and
                   ('staging' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc8') }}"
    - mirror: "{{ clouddata_repo.mirrors_dir }}/{{ cloud.artifacts.repos.soc8.devel.name }}"
      path: "{{ cloud.artifacts.repos.soc8.devel.alias }}"
      name: "{{ cloud.artifacts.repos.soc8.devel.name }}"
      alias: "{{ cloud.artifacts.repos.soc8.devel.alias }}"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc8.devel.enabled | bool) and
                   ('devel' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc8') }}"
    - mirror: "{{ clouddata_repo.mirrors_dir }}/{{ cloud.artifacts.repos.soc8.updates.name }}"
      path: "{{ cloud.artifacts.repos.soc8.updates.alias }}"
      name: "{{ cloud.artifacts.repos.soc8.updates.name }}"
      alias: "{{ cloud.artifacts.repos.soc8.updates.alias }}"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc8.updates.enabled | bool) and
                   ('updates' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc8') }}"
    - mirror: "{{ clouddata_repo.mirrors_dir }}/{{ cloud.artifacts.repos.soc8.pool.name }}"
      path: "{{ cloud.artifacts.repos.soc8.pool.alias }}"
      name: "{{ cloud.artifacts.repos.soc8.pool.name }}"
      alias: "{{ cloud.artifacts.repos.soc8.pool.alias }}"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc8.pool.enabled | bool) and
                   ('pool' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc8') }}"

    # HPE Helion OpenStack Cloud 8 Repos
    - mirror: "{{ clouddata_repo.mirrors_dir }}/{{ cloud.artifacts.repos.hos8.devel.name }}"
      path: "{{ cloud.artifacts.repos.hos8.devel.alias }}"
      name: "{{ cloud.artifacts.repos.hos8.devel.name }}"
      alias: "{{ cloud.artifacts.repos.hos8.devel.alias }}"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.hos8.devel.enabled | bool) and
                   ('devel' in cloud.config.enabled_repos) and
                   (_clm_version == 'hos8') }}"
    - mirror: "{{ clouddata_repo.mirrors_dir }}/{{ cloud.artifacts.repos.hos8.updates.name }}"
      path: "{{ cloud.artifacts.repos.hos8.updates.alias }}"
      name: "{{ cloud.artifacts.repos.hos8.updates.name }}"
      alias: "{{ cloud.artifacts.repos.hos8.updates.alias }}"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.hos8.updates.enabled | bool) and
                   ('updates' in cloud.config.enabled_repos) and
                   (_clm_version == 'hos8') }}"
    - mirror: "{{ clouddata_repo.mirrors_dir }}/{{ cloud.artifacts.repos.hos8.pool.name }}"
      path: "{{ cloud.artifacts.repos.hos8.pool.alias }}"
      name: "{{ cloud.artifacts.repos.hos8.pool.name }}"
      alias: "{{ cloud.artifacts.repos.hos8.pool.alias }}"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.hos8.pool.enabled | bool) and
                   ('pool' in cloud.config.enabled_repos) and
                   (_clm_version == 'hos8') }}"

    #
    # Caching proxy based repos
    #

    # SLES12 SP3 Repos
    - cached_url: "{{ clouddata_repo.base_url }}/{{ sles.artifacts.repos.sles12sp3.updates.name }}"
      name: "{{ sles.artifacts.repos.sles12sp3.updates.name }}-http"
      alias: "{{ sles.artifacts.repos.sles12sp3.updates.alias }}-http"
      distro: sles
      enabled: "{{ sles.artifacts.repos.sles12sp3.updates.enabled | bool }}"
    - cached_url: "{{ clouddata_repo.base_url }}/{{ sles.artifacts.repos.sles12sp3.pool.name }}"
      name: "{{ sles.artifacts.repos.sles12sp3.pool.name }}-http"
      alias: "{{ sles.artifacts.repos.sles12sp3.pool.alias }}-http"
      distro: sles
      enabled: "{{ sles.artifacts.repos.sles12sp3.pool.enabled | bool }}"

    # SUSE OpenStack Cloud 9 Repos
    - cached_url: "{{ clouddata_repo.base_url }}/{{ cloud.artifacts.repos.soc8.staging.name }}"
      name: "{{ cloud.artifacts.repos.soc8.staging.name }}-http"
      alias: "{{ cloud.artifacts.repos.soc8.staging.alias }}-http"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc8.staging.enabled | bool) and
                   ('staging' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc9') }}"
    - cached_url: "{{ clouddata_repo.base_url }}/{{ cloud.artifacts.repos.soc8.devel.name }}"
      name: "{{ cloud.artifacts.repos.soc8.devel.name }}-http"
      alias: "{{ cloud.artifacts.repos.soc8.devel.alias }}-http"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc8.devel.enabled | bool) and
                   ('devel' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc9') }}"
    - cached_url: "{{ clouddata_repo.base_url }}/{{ cloud.artifacts.repos.soc8.updates.name }}"
      name: "{{ cloud.artifacts.repos.soc8.updates.name }}-http"
      alias: "{{ cloud.artifacts.repos.soc8.updates.alias }}-http"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc8.updates.enabled | bool) and
                   ('updates' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc9') }}"
    - cached_url: "{{ clouddata_repo.base_url }}/{{ cloud.artifacts.repos.soc8.pool.name }}"
      name: "{{ cloud.artifacts.repos.soc8.pool.name }}-http"
      alias: "{{ cloud.artifacts.repos.soc8.pool.alias }}-http"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc8.pool.enabled | bool) and
                   ('pool' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc9') }}"

    # HPE Helion OpenStack Cloud 8 Repos
    # SUSE OpenStack Cloud 8 Repos
    # NOTE: currently no DC8S repo for HOS stream, so use SOC DC8S for both modes.
    - cached_url: "{{ clouddata_repo.base_url }}/{{ cloud.artifacts.repos.soc8.staging.name }}"
      name: "{{ cloud.artifacts.repos.soc8.staging.name }}-http"
      alias: "{{ cloud.artifacts.repos.soc8.staging.alias }}-http"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc8.staging.enabled | bool) and
                   ('staging' in cloud.config.enabled_repos) and
                   ((_clm_version == 'soc8') or (_clm_version == 'hos8')) }}"
    - cached_url: "{{ clouddata_repo.base_url }}/{{ cloud.artifacts.repos.soc8.devel.name }}"
      name: "{{ cloud.artifacts.repos.soc8.devel.name }}-http"
      alias: "{{ cloud.artifacts.repos.soc8.devel.alias }}-http"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc8.devel.enabled | bool) and
                   ('devel' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc8') }}"
    - cached_url: "{{ clouddata_repo.base_url }}/{{ cloud.artifacts.repos.soc8.updates.name }}"
      name: "{{ cloud.artifacts.repos.soc8.updates.name }}-http"
      alias: "{{ cloud.artifacts.repos.soc8.updates.alias }}-http"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc8.updates.enabled | bool) and
                   ('updates' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc8') }}"
    - cached_url: "{{ clouddata_repo.base_url }}/{{ cloud.artifacts.repos.soc8.pool.name }}"
      name: "{{ cloud.artifacts.repos.soc8.pool.name }}-http"
      alias: "{{ cloud.artifacts.repos.soc8.pool.alias }}-http"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.soc8.pool.enabled | bool) and
                   ('pool' in cloud.config.enabled_repos) and
                   (_clm_version == 'soc8') }}"

    # HPE Helion OpenStack Cloud 8 Repos
    # NOTE: currently no DC8S repo for HOS stream, so use SOC DC8S above for both modes.
    - cached_url: "{{ clouddata_repo.base_url }}/{{ cloud.artifacts.repos.hos8.devel.name }}"
      name: "{{ cloud.artifacts.repos.hos8.devel.name }}-http"
      alias: "{{ cloud.artifacts.repos.hos8.devel.alias }}-http"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.hos8.devel.enabled | bool) and
                   ('devel' in cloud.config.enabled_repos) and
                   (_clm_version == 'hos8') }}"
    - cached_url: "{{ clouddata_repo.base_url }}/{{ cloud.artifacts.repos.hos8.updates.name }}"
      name: "{{ cloud.artifacts.repos.hos8.updates.name }}-http"
      alias: "{{ cloud.artifacts.repos.hos8.updates.alias }}-http"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.hos8.updates.enabled | bool) and
                   ('updates' in cloud.config.enabled_repos) and
                   (_clm_version == 'hos8') }}"
    - cached_url: "{{ clouddata_repo.base_url }}/{{ cloud.artifacts.repos.hos8.pool.name }}"
      name: "{{ cloud.artifacts.repos.hos8.pool.name }}-http"
      alias: "{{ cloud.artifacts.repos.hos8.pool.alias }}-http"
      distro: sles
      enabled: "{{ (cloud.artifacts.repos.hos8.pool.enabled | bool) and
                   ('pool' in cloud.config.enabled_repos) and
                   (_clm_version == 'hos8') }}"

    #
    # Override repo - hosts locally built RPMs that we want to supersede
    # any versions available in standard SOC/CLM sources, except for the
    # PTF repo.
    #
    - override: "{{ dev_env_working_dir | dirname }}/NEW_RPMS"
      path: "C8-Local"
      name: "Locally built overrides packages"
      alias: "C8-Local"
      priority: 98
      distro: sles
      enabled: True

    # TODO(fergal) Add optional yum extras repo tarball info with tarball
    # rather than mirror attribute here.
  deployer:
    init_pkgs:
      - patterns-cloud-ardana
