#
# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Setup permissions to use QEMU/KVM directly
---
- name: dev-env-kvm | setup-access | Get kvm device ACLs
  command: getfacl /dev/kvm
  changed_when: false
  register: _kvm_facls

- name: dev-env-kvm | setup-access | Set whether kvm file ACLs to be updated
  set_fact:
    _kvm_facls_required: "{{ _kvm_facls.stdout.find('user:' ~ ansible_user_id ~ ':rw-') < 0 }}"

# only add the user to the kvm group if not already being granted access to
# /dev/kvm, which is done by systemd automatically on some distros
- name: dev-env-kvm | setup-access | Add user to kvm group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: kvm
  when:
    - _kvm_facls_required

# add after group permissions are updated to ensure have immediate access
- name: dev-env-kvm | setup-access | Add user to kvm device
  become: yes
  command: setfacl -m "u:{{ ansible_user_id }}:rw-" /dev/kvm
  when:
    - _kvm_facls_required
