# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "baremettle/ubuntu-14.04"

  config.vm.provider "libvirt" do |domain, override|
    domain.memory = 8192
    domain.cpus = 2
  end

  if ENV["http_proxy"]
      config.proxy.http = ENV["http_proxy"]
  end
  if ENV["https_proxy"]
      config.proxy.https = ENV["https_proxy"]
  end
  if ENV["no_proxy"]
      config.proxy.no_proxy = ENV["no_proxy"]
  end
end
