#!/bin/bash
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

mkdir -p ~/.pip
cat > ~/.pip/pip.conf <<EOF
[global]
index-url = $DIB_PYPI_MIRROR_URL
extra-index-url = $DIB_PYPI_MIRROR_URL
trusted-host = $DIB_PYPI_TRUSTED_HOST
EOF

cat > ~/.pydistutils.cfg <<EOF
[easy_install]
index_url = $DIB_PYPI_MIRROR_URL
EOF

