#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Settings used to install & manage the vagrant runtime environment
---

# The user specified version, defaulting to 2.2.9; 2.0.* versions may
# have issues with network setup for RHEL/CentOS computes.
vagrant_version: "{{ lookup('env', 'ARDANA_VAGRANT_VERSION') | default('2.2.9', true) }}"

# From the version we extract the major and minor version values and use
# them to construct a "series" version, which is then used to determine
# the necessary actions required to install vagrant and required plugins
vagrant_series: "{{ vagrant_version.split('.')[0:2] | join('.') }}"

# The VAGRANT_HOME env var, default ~/.vagrant.d/, determines where the
# vagrant plugins live.
vagrant_home: "{{ lookup('env', 'VAGRANT_HOME') |
                  default(ansible_env.HOME ~ '/.vagrant.d', true) }}"

# The plugins.json file holds details on the set of installed plugins
# and the version of vagrant that they are built for.
vagrant_plugins_json: "{{ vagrant_home }}/plugins.json"

# Settings related to downloading Vagrant packages
vagrant_download:
  #Upstream Hashicorp server access problems for Legacy CI systems
  #url_base: "https://releases.hashicorp.com/vagrant"
  url_base: "http://ardana.ci.prv.suse.net/vagrant"
  cache_dir: "{{ ardana_cache_vagrant_dir }}"

# vagrant-libvirt plugin version
vagrant_libvirt_version: 0.4.1

vagrant_requirements:
  pkgs:
    suse:
      - gcc-c++
      - libvirt-devel
      - make
      - patch
      - pkg-config
    debian:
      common:
        - build-essential
        - libvirt-dev
        - pkg-config
      14:
        - libvirt-bin
      16:
        - libvirt-bin
      18:
        - libvirt-clients
        - libvirt-daemon-system
      20:
        - libvirt-clients
        - libvirt-daemon-system

vagrant_common_plugins:
  - name: "vagrant-proxyconf"
    version: "1.5.2"
  - name: "vagrant-libvirt"
    version: "{{ vagrant_libvirt_version }}"
    patch:
      file: "vagrant-libvirt-plugin-{{ vagrant_libvirt_version }}/ardana_enhancements.patch"

vagrant_series_settings:
  series:
    # The 1.7 and 1.8 series upstream Vagrant releases are no longer
    # viable for build the vagrant-libvirt plugin due to ruby/gem
    # dependency issues,
    "1.9":
      versions:
        plugins: "{{ vagrant_version }}"
        runtime: "{{ vagrant_version }}"
      workarounds:
        suse:
          libreadline:
            "42.3": 6
      gems_dirs:
        - "gems/2.3.4"
      plugins: "{{ vagrant_common_plugins }}"

    "2.0":
      versions:
        plugins: "{{ vagrant_version }}"
        runtime: "{{ vagrant_version }}"
      workarounds:
        suse:
          libreadline:
            "15.0": 7
            "15.1": 7
            "15.2": 7
      gems_dirs:
        - "gems/2.4.4"
      plugins: "{{ vagrant_common_plugins }}"

    "2.1":
      versions:
        plugins: "{{ vagrant_version }}"
        runtime: "{{ vagrant_version }}"
      workarounds:
        suse:
          libreadline:
            "15.0": 7
            "15.1": 7
            "15.2": 7
      gems_dirs:
        - "gems/2.4.4"
      plugins: "{{ vagrant_common_plugins }}"

    "2.2":
      versions:
        plugins: "{{ vagrant_version }}"
        runtime: "{{ vagrant_version }}"
      workarounds:
        suse:
          libreadline:
            "15.0": 7
            "15.1": 7
            "15.2": 7
      gems_dirs:
        - "gems/2.4.4"
        - "gems/2.4.6"
        - "gems/2.4.9"
        - "gems/2.6.6"
        - "gems/2.6.7"
        - "gems/2.7.4"  # For Vagrant 2.2.18
        - "gems/3.0.1"  # Used in Vagrant 2.2.17 which fails for other reasons
      plugins: "{{ vagrant_common_plugins }}"

vagrant_settings: "{{ vagrant_series_settings.series[vagrant_series] }}"

vagrant_runtime_version: "{{ vagrant_settings.versions.runtime }}"
vagrant_plugins_version: "{{ vagrant_settings.versions.plugins |
                             default(vagrant_runtime_version) }}"
