#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Misc files that need to be packaged in the deployer
# They are put into the deployer-misc directory so that when combined with all
# of the other ansible repositories they do not lose the directory they should be in
---

- name: deployer | _get_deployer_files | Copy input model to scratch area
  delegate_to: localhost
  synchronize:
    src: "{{ item.value | find_local_repo }}/"
    dest: "{{ item.value.dest }}"
    rsync_opts: >
      --exclude=.git*
      --exclude=*.pyc
    copy_links: yes
    recursive: yes
    delete: yes
  with_dict: deployer_input_model_repositories

- name: deployer | _get_deployer_files | Create merged Ansible distribution
  synchronize:
    src: "{{ item.value | find_local_repo }}/"
    dest: "{{ deployer_ansible_dir }}"
    copy_links: yes
    rsync_opts: >
      --exclude=.git*
      --exclude=*.pyc
      --exclude=ardana-ci/*
  with_dict: deployer_git_repositories

- name: deployer | _get_deployer_files | Transfer all callback plugins
  synchronize:
    src: "{{ dev_env_working_dir }}/ansible/callback_plugins"
    dest: "{{ deployer_ansible_dir }}"
    copy_links: yes
    rsync_opts: >
      --exclude=.git*
      --exclude=*.pyc

- name: deployer | _get_deployer_files | Transfer selected filter plugins
  synchronize:
    src: "{{ dev_env_working_dir }}/ansible/filter_plugins/{{ item }}"
    dest: "{{ deployer_ansible_dir }}/filter_plugins/"
    rsync_opts: >
      --exclude=.git*
      --exclude=*.pyc
  with_items: deployer_filter_plugins

- name: deployer | _get_deployer_files | Transfer constant roles
  synchronize:
    src: "{{ dev_env_working_dir }}/ansible/roles/package-constants/defaults"
    dest: "{{ deployer_ansible_dir }}/roles/package-constants"
    rsync_opts: >
      --exclude=.git*
      --exclude=*.pyc

- name: deployer | _get_deployer_files | Transfer all deployer modules
  synchronize:
    src: "{{ dev_env_working_dir }}/ansible/deployer_modules/"
    dest: "{{ deployer_ansible_dir }}/library"
    copy_links: yes
    rsync_opts: >
      --exclude=.git*
      --exclude=*.pyc

- name: deployer | _get_deployer_files | Create human readable version file
  template:
    src: ardana_version.j2
    dest: "{{ deployer_ansible_dir }}/Ardana_version"


- name: deployer | _get_deployer_files | Create a machine readable version file
  template:
    src: ardana_version.yml.j2
    dest: "{{ deployer_ansible_dir }}/ardana_version.yml"

- name: deployer | _get_deployer_files | Gather ardana-extensions repo contents
  synchronize:
    src: "{{ item.value | find_local_repo }}/"
    dest: "{{ deployer_ardana_extensions_dir }}"
    copy_links: yes
    rsync_opts: >
      --exclude=.git*
      --exclude=*.pyc
  with_dict: deployer_ardana_extensions_repositories
