#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Install internal code for QA. This code will not be going to customers.
---

# TODO(fergal): Hack to work around the fact that the SUSEified ardana-init
# script is not tracking ardana version information as configured in the
# ardana-dev-tools/ansible/roles/product-ardana settings.
# remove once SUSEified deployer version setting matches the value specified
# in ardana-dev-tools.
# start-of-hack
- name: deployer | setup-qa-tests | determine deployer version
  set_fact:
    _deployer_version: "{{ deployer_version }}"
  when: _deployer_version is not defined
# end-of-hack

- name: deployer | setup-qa-tests | Push local source repos onto deployer
  synchronize:
    src: "{{ item.value | find_local_repo }}/"
    dest: "/home/{{ image_build_user }}/{{ item.value.url | basename }}"
    copy_links: yes
    recursive: yes
    delete: yes
    compress: no
  with_dict: "{{ deployer_qa_git_repositories | default({}) }}"

- name: deployer | setup-qa-tests | Evaluate target dir
  set_fact:
    setup_qa_tests_dir: |
      {{ PACKAGE_CONSTANTS.REPO_DIR }}/{{ _deployer_version }}/{{
          package_venv_locations.sles[ansible_architecture] }}

# Install deployer_nondist_venvs directly into /opt/ardana_packager
- name: deployer | setup-qa-tests | Copy nondist venv packages into the deployer
  become: yes
  copy:
    src: "{{ venv_cache_dir }}/{{ item.value.1 }}"
    dest: "{{ setup_qa_tests_dir }}"
  when: item.key in packages_nondist
  with_dict: "{{ venv_cache_dir | find_latest_packages(_deployer_version) | default({}) }}"

- name: deployer | setup-qa-tests | determine pwd for create_index operation
  set_fact:
    _index_chdir: "{{ PACKAGE_CONSTANTS.SERVICE_DIR }}/packager/venv/bin"
  when: _index_chdir is not defined

# This is a duplication of ardana-ansible/roles/package-repo/tasks/configure.yml
- name: deployer | setup-qa-tests | Update venv index
  become: yes
  command: >-
    ./create_index
    --dir={{ setup_qa_tests_dir }}
  args:
    chdir: "{{ _index_chdir }}"
