# (c) Copyright 2015 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

---

- block:
  - name: dev-env | ansible | Ansible version correct?
    debug:
      msg: >
        Development environment requires specific versions of Ansible and some
        dependencies. Please re-run the '{{ dev_env_working_dir }}/dev-env-setup'
        script, or the 'astack.sh' script without the '--no-setup' option, to
        setup the correct Ansible runtime environment.

  - name: dev-env | ansible | Ansible runtime activated?
    debug:
      msg: >
        Or did you forget to run 'eval $({{ dev_env_working_dir }}/ardana-env)'
        if running commands manyally?

  - name: dev-env | ansible | Fail due to Ansible runtime environment issues
    fail:
      msg: "Unsupported Ansible runtime environment detected"
  when:
    - (detected_ansible_version == "") or
      (detected_ansible_version | version_compare_smart(dev_env_ansible_version, "lt"))
