#!/bin/bash
# Add the ardana user we recommend folk use.

set -eu
set -o xtrace

ARDANAUSER=${ARDANAUSER:-"ardana"}
ARDANA_USER_HOME_BASE=${ARDANA_USER_HOME_BASE:-"/home"}

useradd -b ${ARDANA_USER_HOME_BASE} -m $ARDANAUSER -s /bin/bash

passwd $ARDANAUSER <<EOF
$ARDANAUSER
$ARDANAUSER
EOF


cat > /etc/sudoers.d/$ARDANAUSER <<eof
# the ardana user sometimes requires passwordless
# sudo for scripted operations.
$ARDANAUSER ALL=(ALL) NOPASSWD:ALL
eof

chmod 0440 /etc/sudoers.d/$ARDANAUSER
visudo -c

if [ -e "/tmp/in_target.d/ssh-authorized-keys" ]; then
    mkdir -p ${ARDANA_USER_HOME_BASE}/$ARDANAUSER/.ssh
    cat /tmp/in_target.d/ssh-authorized-keys >> ${ARDANA_USER_HOME_BASE}/$ARDANAUSER/.ssh/authorized_keys
    chown -R $ARDANAUSER:$ARDANAUSER ${ARDANA_USER_HOME_BASE}/$ARDANAUSER/.ssh
fi
