#
# (c) Copyright 2015-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: venv | _clear | Invalidate complete for service
  file:
    dest: "{{ VENV.STATE_DIR }}/{{ service }}.complete"
    state: absent
  register: _venv_check_invalidate_result

- name: venv | _clear | Register service details for service
  template:
    src: service.j2
    dest: "{{ VENV.STATE_DIR }}/{{ service }}.service"
  register: _venv_service_result

- set_fact:
    _venv_service_complete: "{{ _venv_check_invalidate_result.changed and
        not _venv_service_result.changed and
        not rebuild }}"

- name: venv | _clear | Get previous version when present
  shell:
    cat {{ VENV.STATE_DIR }}/{{ service }}.version
  register: _current_version_result
  when: _venv_service_complete|bool

- name: venv | _clear | Check MD5SUM of file to catch any corruption in these files
  shell:
    md5sum --strict --check "{{ VENV.STATE_DIR }}/{{ service }}.md5sum"
  register: _check_tarfile_md5sum_result
  failed_when: false
  changed_when: _check_tarfile_md5sum_result.rc != 0
  when: _venv_service_complete|bool

- name: venv | _clear | Debug when we fail md5sum
  debug: var=_check_tarfile_md5sum_result
  when: _venv_service_complete|bool and _check_tarfile_md5sum_result|failed

- name: venv | _clear | Mark service complete if no new updates are detected
  file:
    dest: "{{ VENV.STATE_DIR }}/{{ service }}.complete"
    state: touch
  when: _venv_service_complete|bool and _check_tarfile_md5sum_result|success

- name: venv | _clear | Stat service complete markers
  stat:
    path: "{{ VENV.STATE_DIR }}/{{ service }}.complete"
  register: _venv_service_complete_stat_result
