#
# (c) Copyright 2015 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Install extra service files into the virtual environment build directory.
# The directory structure is controlled directly from the layout of the YAML
# in default/main.yml '_services_default'. Example is as follows:
#
# _services_default:
#   nova:
#    sources:
#       nova:
#         - file_a
#         - dir_b
#         - ...
#       oslo.messaging:
#         - file_a
#         - dir_c
#         - ...
#
# The above '_services_default' YAML for the 'nova' components will copy
# any directory recursively and places the content in directory’s in the
# 'PACKAGE_CONSTANTS.INSTALL_DIR' which will be in the exported nova-<<version>>.tar file.
#
# /PACKAGE_CONSTANTS.INSTALL_DIR/nova/share/nova/file_a
# /PACKAGE_CONSTANTS.INSTALL_DIR/nova/share/nova/dir_b/...
# /PACKAGE_CONSTANTS.INSTALL_DIR/nova/share/nova/...
# /PACKAGE_CONSTANTS.INSTALL_DIR/nova/share/oslo.messaging/file_a
# /PACKAGE_CONSTANTS.INSTALL_DIR/nova/share/oslo.messaging/dir_c/...
# /PACKAGE_CONSTANTS.INSTALL_DIR/nova/share/oslo.messaging/...
---

- name: venv | _install-share | Create share in the virtual environment for service
  file:
    path: "{{ PACKAGE_CONSTANTS.INSTALL_DIR }}/{{ service }}-{{ version }}/share/{{ item.keys()[0] }}"
    state: directory
  when: item.keys() is defined
  with_items: services[service].sources | default([])

- name: venv | _install-share | Copy additional data in to virtual environment for service
  command: >
    rsync --delete -iac
    "{{ VENV.SRC_DIR }}/{{ _venv_ardana_sources[ item.0 ] | venv_source_build_dest }}/{{ item.1 }}"
    "{{ PACKAGE_CONSTANTS.INSTALL_DIR }}/{{ service }}-{{ version }}/share/{{ item.0 }}"
  with_items: services[service].sources | default([]) | extract_dicts | unzip
  register: rsync_result
  changed_when: rsync_result.stdout
