#
# (c) Copyright 2016-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Setup patched virtualenv when required
---
- name: venv | setup-virtualenv | Deploy empty virtualenv.ini
  command: touch /home/{{ image_build_user }}/.virtualenv/empty
  args:
    creates: /home/{{ image_build_user }}/.virtualenv/empty
  when: (ansible_os_family | lower == 'redhat') or
        (ansible_os_family.split(' ')[0] | lower | replace('open','') == 'suse')

- name: venv | setup-virtualenv | Setup virtualenv
  pip:
    virtualenv: "{{ _venv_virtualenv_command | dirname | dirname }}"
    state: present
    name: pip virtualenv setuptools<34.0.0 wheel
    extra_args: >-
      --upgrade
      --timeout 30
  environment:
    VIRTUALENV_CONFIG_FILE: /home/{{ image_build_user }}/.virtualenv/empty

- name: venv | setup-virtualenv | Patch virtualenv for RHEL
  lineinfile:
    dest: ~/virtualenv/lib/python2.7/site-packages/virtualenv.py
    backrefs: yes
    regexp: "^(\\s+)copyfile\\('lib', lib64_link\\)"
    line: "\\1copyfile(lib_dir, lib64_link)"
    state: present
  when: (ansible_os_family | lower == 'redhat')

- name: venv | setup-virtualenv | Patch virtualenv for SLES12 set dynload_dirs
  lineinfile:
    dest: ~/virtualenv/lib/python2.7/site-packages/virtualenv.py
    insertbefore: "{{ item.insertbefore }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { insertbefore: "pythonpath = os\\.pathsep\\.join\\(wheels\\)$",
        line: "    dynload_dirs = [d for d in sys.path if d.endswith('/lib-dynload')]"}
  when: ansible_os_family.split(' ')[0] | lower | replace('open','') == 'suse'

- name: venv | setup-virtualenv | Patch virtualenv for SLES12 add dynload_dirs
  lineinfile:
    dest: ~/virtualenv/lib/python2.7/site-packages/virtualenv.py
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: yes
    state: present
  with_items:
    - { regexp: "^(\\s+pythonpath = os\\.pathsep\\.join\\(wheels)(\\))$" ,
        line: "\\1 + dynload_dirs\\2" }
  when: ansible_os_family.split(' ')[0] | lower | replace('open','') == 'suse'

- name: venv | setup-virtualenv | Patch virtualenv for SLES12
  lineinfile:
    dest: ~/virtualenv/lib/python2.7/site-packages/virtualenv.py
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { insertafter: "^is_darwin",
        line: "is_lib64_dynload = any(('/lib64/' in p) and p.endswith('/lib-dynload') for p in sys.path)" }
  when: ansible_os_family.split(' ')[0] | lower | replace('open','') == 'suse'

- name: venv | setup-virtualenv | Patch virtualenv for SLES12 symlink lib64
  lineinfile:
    dest: ~/virtualenv/lib/python2.7/site-packages/virtualenv.py
    backrefs: yes
    regexp: "^(\\s+)fix_lib64\\(lib_dir, symlink\\)"
    line: "\\1fix_lib64(lib_dir, symlink or is_lib64_dynload)"
    state: present
  when: ansible_os_family.split(' ')[0] | lower | replace('open','') == 'suse'
