#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Tasks to install and setup squid as a caching proxy service for zypper
# repo access.
---

- name: vagrant-cloud8-setup | _setup-squid | Install caching proxy packages
  become: yes
  zypper:
    name: "{{ item }}"
    state: "latest"
  with_items: cloud8.deployer.caching_proxy.pkgs

- name: vagrant-cloud8-setup | _setup-squid | Fix proxy cache mount perms
  become: yes
  file:
    path: "{{ item.mount }}"
    owner: "{{ cloud8.deployer.caching_proxy.fs.user }}"
    group: "{{ cloud8.deployer.caching_proxy.fs.group }}"
    mode: "0750"
    state: directory
  with_items: c8setup.caching_proxy.mounts

- name: vagrant-cloud8-setup | _setup-squid | Add/Update cache_dir entry
  become: yes
  lineinfile:
    dest: "{{ cloud8.deployer.caching_proxy.conf.file }}"
    insertafter: '^#cache_dir\s+'
    line: >
      cache_dir
      {{ cloud8.deployer.caching_proxy.conf.type }}
      {{ item.mount }}
      {{ ((item.size_total * 0.80) / (1024 * 1024)) | int }}
      {{ cloud8.deployer.caching_proxy.conf.L1 }}
      {{ cloud8.deployer.caching_proxy.conf.L2 }}
    regexp: '^cache_dir\s+\S+\s+{{ item.mount }}\s+'
    state: present
  with_items: c8setup.caching_proxy.mounts
  register: _update_cache_dir_result

- name: vagrant-cloud8-setup | _setup-squid | Add/Update max obj size
  become: yes
  lineinfile:
    dest: "{{ cloud8.deployer.caching_proxy.conf.file }}"
    insertbefore: '^#cache_dir\s+'
    line: 'maximum_object_size {{ cloud8.deployer.caching_proxy.conf.max_size }}'
    regexp: '^maximum_object_size\s+'
    state: present
  with_items: c8setup.caching_proxy.mounts
  register: _update_max_size_result

- name: vagrant-cloud8-setup | _setup-squid | Add/Update replacement policy
  become: yes
  lineinfile:
    dest: "{{ cloud8.deployer.caching_proxy.conf.file }}"
    insertafter: '^cache_dir\s+'
    line: 'cache_replacement_policy {{ cloud8.deployer.caching_proxy.conf.policy }}'
    regexp: '^cache_replacement_policy\s+'
    state: present
  with_items: c8setup.caching_proxy.mounts
  register: _update_repl_policy_result

- name: vagrant-cloud8-setup | _setup-squid | Allow port 79
  become: yes
  lineinfile:
    dest: "{{ cloud8.deployer.caching_proxy.conf.file }}"
    insertbefore: '^acl Safe_ports port 80'
    line: 'acl Safe_ports port 79		# deployer http'
    regexp: '^acl\s+Safe_ports\s+port\s+79\s+'
    state: present
  with_items: c8setup.caching_proxy.mounts
  register: _update_allow_port_result

- name: vagrant-cloud8-setup | _setup-squid | Update http_port entry
  become: yes
  lineinfile:
    dest: "{{ cloud8.deployer.caching_proxy.conf.file }}"
    insertafter: '^# Squid normally listens to port'
    line: 'http_port {{ cloud8.deployer.caching_proxy.conf.port }}'
    regexp: '^http_port\s+\S+'
    state: present
  with_items: c8setup.caching_proxy.mounts
  register: _update_http_port_result

- name: vagrant-cloud8-setup | _setup-squid | Restart proxy service if needed
  become: yes
  service:
    name: "{{ cloud8.deployer.caching_proxy.conf.svc }}"
    state: restarted
  when:
    - ((_update_cache_dir_result | changed) or
       (_update_max_size_result | changed) or
       (_update_repl_policy_result | changed) or
       (_update_allow_port_result | changed) or
       (_update_http_port_result | changed))

- name: vagrant-cloud8-setup | _setup-squid | Ensure proxy service enabled and started
  become: yes
  service:
    name: "{{ cloud8.deployer.caching_proxy.conf.svc }}"
    enabled: yes
    state: started
