# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 :

require File.expand_path(File.dirname(__FILE__)) + "/../../lib/ardana_vagrant_helper.rb"

cloud_name = "entry-scale-swift"
deployer_node = "controller1"

Vagrant.configure("2") do |config|

  ardana = Ardana::Config.new config
  ardana.set_ssh_config

  # Provider-specific settings
  ardana.set_provider_config

  ardana.set_vm_config

  # Server Definitions
  # Control & Compute nodes
  ardana.add_server_group(modifier: 1, cloud_name: cloud_name, deployer_node: deployer_node)
end
