#!/opt/stack/venvs/packager/bin/python
#
# (c) Copyright 2015 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

def main():
    module = AnsibleModule(
        argument_spec = dict(
            state = dict(choices=['present', 'absent'], default=None, required=True),
            name = dict(required=True),
            version = dict(default=None),
        ),
        supports_check_mode = False
    )

    params = module.params
    state = params['state']
    name = params['name']
    version = params['version']

    module.exit_json(state=state, name=name, version=version, changed=False)

from ansible.module_utils.basic import *
if __name__ == '__main__':
    main()
