#!/bin/bash
#
# (c) Copyright 2014-2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

set -eux
set -o pipefail

if [ -f ${TARGET_ROOT}/.distro-name ] ; then
    DISTRO_NAME=$(cat ${TARGET_ROOT}/.distro-name)
else
    DISTRO_NAME=${DIB_DEBIAN_DISTRO_NAME:-debian}
fi
DIB_RELEASE=${DIB_RELEASE:-unstable}
DEBOOTSTRAP_TARBALL=$DIB_IMAGE_CACHE/debootstrap-${DISTRO_NAME}-${DIB_RELEASE}-${ARCH}.tar.gz
if [ -n "${DIB_DEBIAN_MIRROR:-}" ]; then
    echo "Use of DIB_DEBIAN_MIRROR environment variable to configure mirror is deprecated."
    echo "Please use DIB_DISTRIBUTION_MIRROR instead."
    DIB_DISTRIBUTION_MIRROR=$DIB_DEBIAN_MIRROR
fi
DIB_DISTRIBUTION_MIRROR=${DIB_DISTRIBUTION_MIRROR:-http://http.debian.net/debian}
if [ -z "${SKIP_APT_PROXY:-}" ] ; then
    http_proxy=${http_proxy:-}
    no_proxy=${no_proxy:-}
else
    http_proxy=
    no_proxy=
fi

echo "Building new tarball for Debian $DIB_RELEASE ARCH=$ARCH"
if [ -n "${DIB_DEBIAN_INITIAL_PACKAGES:-}" ] ; then
    ADD_PACKAGES="$DIB_DEBIAN_INITIAL_PACKAGES"
else
    ADD_PACKAGES="python,sudo,adduser,locales,openssh-server,file,less,kbd,curl"
    ADD_PACKAGES="${ADD_PACKAGES},rsync,bash-completion,linux-image-amd64,dbus"
fi
if [ -f ${TARGET_ROOT}/.extra-packages ] ; then
    ADD_PACKAGES=${ADD_PACKAGES},$(cat ${TARGET_ROOT}/.extra-packages)
fi
ADD_PACKAGES="$ADD_PACKAGES,linux-headers-amd64"

# Use the hlinux-archive-keyring file to check signatures
# of retrieved Release files. If this changes this needs updating.
sudo sh -c "http_proxy=$http_proxy no_proxy=$no_proxy \
   debootstrap --verbose \
   --arch=${ARCH} \
   --include=${ADD_PACKAGES} \
   --keyring=$(dirname $0)/hlinux-archive-keyring.gpg \
   $DIB_RELEASE \
   $TARGET_ROOT \
   $DIB_DISTRIBUTION_MIRROR \
   ${DIB_DEBIAN_DEBOOTSTRAP_SCRIPT:-}"

echo "Customizing result for cloud use"
sudo sed -i "s/PermitRootLogin yes/PermitRootLogin without-password/" \
    $TARGET_ROOT/etc/ssh/sshd_config
sudo chroot ${TARGET_ROOT} adduser --gecos Debian-cloud-init-user --disabled-password \
    --quiet debian
sudo install -d -m 0755 -o root -g root ${TARGET_ROOT}/etc/sudoers.d
sudo sh -c "echo 'debian ALL=(ALL) NOPASSWD:ALL' \
   > ${TARGET_ROOT}/etc/sudoers.d/debian-cloud-init"
sudo chmod 0440 ${TARGET_ROOT}/etc/sudoers.d/debian-cloud-init
sudo sh -c "echo 'proc /proc proc nodev,noexec,nosuid 0 0
LABEL=cloudimg-rootfs / ext4 errors=remount-ro 0 0
' > ${TARGET_ROOT}/etc/fstab"
sudo sh -c "echo 'blacklist pcspkr' > ${TARGET_ROOT}/etc/modprobe.d/blacklist.conf"

# cloud images expect eth0 to use dhcp.
sudo mkdir -p ${TARGET_ROOT}/etc/network/interfaces.d
cat << EOF | sudo tee ${TARGET_ROOT}/etc/network/interfaces.d/eth0
# The primary network interface
auto eth0
iface eth0 inet dhcp
EOF
