#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Repositories to add into the deployer package
---
# The deployer version is the next release we are working against
deployer_version: "{{ product_name_version_release }}"

deployer_git_update : "{{ dev_env_global_git_update }}"

_deployer_branch_default: "{{ product_branch }}"
_deployer_legacy_branch_default: "stable/pike"
_deployer_eon_branch_default: "master"

_deployer_git_repositories_default:
  barbican-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/barbican-ansible"
    branch: "{{ _deployer_branch_default }}"
  cassandra-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/cassandra-ansible"
    branch: "{{ _deployer_branch_default }}"
  ceilometer-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/ceilometer-ansible"
    branch: "{{ _deployer_branch_default }}"
  cinder-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/cinder-ansible"
    branch: "{{ _deployer_branch_default }}"
  cluster-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/cluster-ansible"
    branch: "{{ _deployer_branch_default }}"
  cobbler-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/cobbler-ansible"
    branch: "{{ _deployer_branch_default }}"
  db-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/db-ansible"
    branch: "{{ _deployer_branch_default }}"
  designate-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/designate-ansible"
    branch: "{{ _deployer_branch_default }}"
  # NOTE: HPE references in EON repo specs here are safe to keep,
  # in rebranding terms, as they are references to HPE's opensourced
  # version of the EON code as used in previous releases
  eon-ansible:
    url: "{{ dev_env_git_servers.github }}/hpe-helion-os/hpe-eon-ansible"
    branch: "{{ _deployer_eon_branch_default }}"
  freezer-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/freezer-ansible"
    branch: "{{ _deployer_branch_default }}"
  glance-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/glance-ansible"
    branch: "{{ _deployer_branch_default }}"
  heat-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/heat-ansible"
    branch: "{{ _deployer_branch_default }}"
  ardana-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/ardana-ansible"
    branch: "{{ _deployer_branch_default }}"
  horizon-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/horizon-ansible"
    branch: "{{ _deployer_branch_default }}"
  icinga-ansible:
    url: "{{ dev_env_default_git_server }}/hp/icinga-ansible"
    branch: "hp/prerelease/newton"
  ironic-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/ironic-ansible"
    branch: "{{ _deployer_branch_default }}"
  keystone-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/keystone-ansible"
    branch: "{{ _deployer_branch_default }}"
  logging-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/logging-ansible"
    branch: "{{ _deployer_branch_default }}"
  magnum-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/magnum-ansible"
    branch: "{{ _deployer_branch_default }}"
  memcached-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/memcached-ansible"
    branch: "{{ _deployer_branch_default }}"
  monasca-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/monasca-ansible"
    branch: "{{ _deployer_branch_default }}"
  mq-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/mq-ansible"
    branch: "{{ _deployer_branch_default }}"
  neutron-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/neutron-ansible"
    branch: "{{ _deployer_branch_default }}"
  nova-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/nova-ansible"
    branch: "{{ _deployer_branch_default }}"
  octavia-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/octavia-ansible"
    branch: "{{ _deployer_branch_default }}"
  ops-console-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/opsconsole-ansible"
    branch: "{{ _deployer_branch_default }}"
  osconfig-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/osconfig-ansible"
    branch: "{{ _deployer_branch_default }}"
  server-ansible:
    url: "{{ dev_env_default_git_server }}/hp/server-ansible"
    branch: "hp/prerelease/newton"
  sherpa-ansible:
    url: "{{ dev_env_default_git_server }}/hp/sherpa-ansible"
    branch: "hp/prerelease/newton"
  spark-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/spark-ansible"
    branch: "{{ _deployer_branch_default }}"
  monasca-transform-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/monasca-transform-ansible"
    branch: "{{ _deployer_branch_default }}"
  swift-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/swift-ansible"
    branch: "{{ _deployer_branch_default }}"
  tempest-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/tempest-ansible"
    branch: "{{ _deployer_branch_default }}"
  tls-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/tls-ansible"
    branch: "{{ _deployer_branch_default }}"
  ardana-service-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/ardana-service-ansible"
    branch: "{{ _deployer_branch_default }}"

deployer_git_repositories: "{{ _deployer_git_repositories_default |
                               update(deployer_git_repositories_update |
                                      default({})) }}"

deployer_input_model_repositories:
  ardana-input-model:
    url: "{{ dev_env_default_git_server }}/ardana/ardana-input-model"
    branch: "{{ _deployer_branch_default }}"
    dest: "{{ deployer_input_model_dir }}/ardana-input-model"

deployer_qa_git_repositories:
  ardana-qa-ansible:
    url: "{{ dev_env_default_git_server }}/ardana/ardana-qa-ansible"
    branch: "{{ _deployer_branch_default }}"
  ardana-qa-tests:
    url: "{{ dev_env_default_git_server }}/ardana/ardana-qa-tests"
    branch: "{{ _deployer_branch_default }}"
