#
# (c) Copyright 2015,2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Install vagrant dependencies
---

- name: vagrant | _install_prereqs | install vagrant dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ vagrant_apt_packages }}"
  when: ansible_os_family | lower == "debian"

- name: vagrant | _install_prereqs | install vagrant dependencies
  become: yes
  zypper:
    name: "{{ item }}"
    state: present
  with_items: "{{ vagrant_zypp_packages }}"
  when: ansible_os_family.split(' ')[0] | lower | replace('open','') == "suse"
