#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Tasks to sync mirrored repos to the SOC/CLM deployer
---

- name: cloud-deployer | sync-mirrored-repos | Check mirrored repos exist
  delegate_to: localhost  # run on vagrant host
  stat:
    path: "{{ item.mirror }}"
  with_items: "{{ clmsetup.repos }}"
  register: _mirrored_repos_stat_result
  when:
    - item.mirror is defined
    - item.enabled | bool

- name: cloud-deployer | sync-mirrored-repos | Create mirrored repo targets
  become: yes
  file:
    path: "{{ clmsetup.server[item.item.distro].base }}/{{ clmsetup.distros[item.item.distro].dir }}/{{ item.item.path }}"
    state: directory
    follow: yes
  with_items: "{{ _mirrored_repos_stat_result.results }}"
  when:
    - item is not skipped

- name: cloud-deployer | sync-mirrored-repos | Push mirrored repos up to deployer
  become: true
  synchronize:
    src: "{{ item.item.mirror }}/"
    dest: "{{ clmsetup.server[item.item.distro].base }}/{{ clmsetup.distros[item.item.distro].dir }}/{{ item.item.path }}"
    compress: no
    archive: yes
    delete: yes
  with_items: "{{ _mirrored_repos_stat_result.results }}"
  when:
    - item is not skipped

# The update support playbooks check for the Cloud Pool tag being set
# on the Cloud repos and will fail if it isn't found so we need to cheat
# and add it to the Staging or Devel repos.
- name: cloud-deployer | setup-mirrored-repos | Set cloud pool tag if needed
  become: yes
  lineinfile:
    path: "{{ clmsetup.server[item.item.distro].base }}/{{
              clmsetup.distros[item.item.distro].dir }}/{{
              item.item.path }}/suse/repodata/repomd.xml"
    insertafter: "<tags>"
    line: "    <repo>obsproduct://build.suse.de/SUSE:SLE-{{
                 sles_major }}-SP{{ sles_sp }}:Update:Products:Cloud{{
                 cloud_version }}/{{ item.item.cloud_pool_tag }}/{{
                 cloud_version }}/POOL/x86_64</repo>"
  with_items: "{{ _mirrored_repos_stat_result.results }}"
  when:
    - item is not skipped
    - item.item.cloud_pool_tag is defined


# The update support playbooks check for the Cloud Updates tag being set
# on the Cloud repos and will fail if it isn't found so we need to cheat
# and add it to the Staging or Devel repos.
- name: cloud-deployer | setup-mirrored-repos | Set cloud updates tag if needed
  become: yes
  lineinfile:
    path: "{{ clmsetup.server[item.item.distro].base }}/{{
              clmsetup.distros[item.item.distro].dir }}/{{
              item.item.path }}/suse/repodata/repomd.xml"
    insertafter: "<tags>"
    line: "    <repo>obsrepository://build.suse.de/SUSE:Updates:{{
                 item.item.cloud_updates_tag }}:{{ cloud_version
                 }}:x86_64/update</repo>"
  with_items: "{{ _mirrored_repos_stat_result.results }}"
  when:
    - item is not skipped
    - item.item.cloud_updates_tag is defined
