#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Tasks to sync override repos to the SOC/CLM deployer
---

- name: cloud-deployer | sync-override-repos | Checked override repos exist
  delegate_to: localhost  # run on vagrant host
  stat:
    path: "{{ item.override }}"
  with_items: "{{ clmsetup.repos }}"
  register: _override_repos_stat_result
  when:
    - item.override is defined
    - item.enabled | bool

- name: cloud-deployer | sync-override-repos | Create override repo targets
  become: yes
  file:
    path: "{{ clmsetup.server[item.item.distro].base }}/{{ clmsetup.distros[item.item.distro].dir }}/{{ item.item.path }}"
    state: directory
    follow: yes
  with_items: "{{ _override_repos_stat_result.results }}"
  when:
    - item is not skipped

- name: cloud-deployer | sync-override-repos | Push override repos up to deployer
  become: true
  synchronize:
    src: "{{ item.item.override }}/"
    dest: "{{ clmsetup.server[item.item.distro].base }}/{{ clmsetup.distros[item.item.distro].dir }}/{{ item.item.path }}"
    compress: no
    archive: yes
    delete: yes
  with_items: "{{ _override_repos_stat_result.results }}"
  when:
    - item is not skipped
  register: sync_override_repos_result

# Only trigger if some synchronisation occurred, but ensure that the
# metadata in all overrides repos that have been created on the deployer
# is updated, not just the ones that were sync'd.
- name: cloud-deployer | sync-override-repos | Update repo metadata
  become: true
  shell: |-
    set -e
    cd "{{ clmsetup.server[item.item.distro].base }}/{{ clmsetup.distros[item.item.distro].dir }}/{{ item.item.path }}"
    createrepo --update .
  with_items: "{{ _override_repos_stat_result.results }}"
  when:
    - sync_override_repos_result is not skipped
    - item is not skipped
