#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Package build artefacts into the hlinux ISO
---
- name: isogen | isogen | Validate isogen environment
  fail:
    msg: "Please set the GOZER_BUILD_ID environmental variable. Jenkins does this"
  when: not lookup('env', 'GOZER_BUILD_ID')

- set_fact:
    output_version: "{{ product_name_version }}_{{ lookup('env', 'GOZER_BUILD_ID') }}"

- debug: var=output_version

- set_fact:
    output_iso: "{{ isogen_working_dir }}/output/{{ output_version }}.iso"

- debug: var=output_iso

- set_fact:
    input_iso: "{{ hlinux_iso }}"
  when: not isogen_produce_sles_iso

- set_fact:
    input_iso: "{{ sles12_iso }}"
  when: isogen_produce_sles_iso

- debug: var=input_iso

# Run isogen
- name: isogen | isogen | Run isogen
  shell: ./create_iso.sh \
      -d {{ deployer_tarball }} \
      -o {{ output_iso }} \
      {{ input_iso }} \
      {{ hlinux_artefacts_dir }}/ova/hlinux.ova \
      {{ hlinux_artefacts_dir }}/hlinux.qcow2
  args:
    chdir: "{{ isogen_working_dir }}"

- name: isogen | isogen | Save full ISO
  include: ../../artifact-publisher/tasks/save-artifact.yml
  vars:
    type: "ardana-iso"
    branch: "{{ product_branch }}"
    version: "{{ output_version }}"
    filename: "{{ output_iso }}"

# Remove the isogen scratch directories since some parts
# of them are root-owned, and can cause problems (e.g. for
# jenkins during workspace cleanup)
- name: isogen | isogen | Remove isogen/scratch
  become: yes
  file:
    path: "{{ isogen_working_dir }}/scratch"
    state: absent

- name: isogen | isogen | Clean isogen/scratch_initrd
  become: yes
  file:
    path: "{{ isogen_working_dir }}/scratch_initrd"
    state: absent
