#
# (c) Copyright 2019 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Reboot a node, wait for a reconnect and confirm that it rebooted
# successfully.
---

- name: reboot-node | main | Reboot the node
  become: yes
  shell: >-
    sleep 2 &&
    shutdown -r now "{{ reboot_msg }}"
  async: 1
  poll: 0
  failed_when: false

- name: reboot-node | main | Wait for node to come back up
  wait_for_connection:
    delay: "{{ reboot_delay }}"
    sleep: "{{ reboot_sleep }}"
    timeout: "{{ reboot_timeout }}"
    connect_timeout: "{{ reboot_connect_timeout }}"

- name: reboot-node | main | Refresh node facts
  setup:

- name: reboot-node | main | Confirm node rebooted successfully
  fail:
    msg: >-
      Node '{{ inventory_hostname }}' failed to reboot successfully.
  when:
    - (ansible_uptime_seconds | int) > (reboot_max_uptime | int)
