#
# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 :

require File.expand_path(File.dirname(__FILE__)) + "/../../lib/ardana_vagrant_helper.rb"

cloud_name = "virtual-control-plane"
deployer_node = "vmfactory1"

Vagrant.configure("2") do |config|

  ardana = Ardana::Config.new config
  ardana.set_ssh_config

  # Provider-specific settings
  ardana.set_provider_config

  ardana.set_vm_config

  # Server Definitions
  # Control & Compute nodes
  ardana.add_server_group(modifier: 1, cloud_name: cloud_name, deployer_node: deployer_node)
end
