#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Main playbook for setting up a SOC/CLM deployment within a target cloud
---

- import_playbook: cloud-vm-setup.yml

- import_playbook: cloud-buildservice-repos.yml

- import_playbook: cloud-deployer-repos.yml

- import_playbook: cloud-deployer-init.yml

- import_playbook: cloud-remote-repos.yml

- import_playbook: cloud-refresh-repos.yml

- import_playbook: sync-ansible-sources.yml
