#
# (c) Copyright 2015 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Top level playbook to setup guest VM accesss in the developer environment
---

# Execute ansible task to setup guest VM accesss the development environment
- hosts: localhost
  become: yes
  connection: local
  roles:
    - dev-env
  tasks:
    - include_tasks: roles/dev-env/tasks/connect_deployer_to_extnet.yml
