#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Build the vagrant image for the developer environment
---

- include: image-build-setup.yml

- hosts: localhost
  connection: local
  roles:
    - image-build
    - apt-repos
  tasks:
    - include: roles/image-build/tasks/build-packer-qcow2.yml
      vars:
        image_build_iso: "{{ rhel7_iso }}"
        image_build_name: rhel-7
        image_build_disk_size: 4120
      when: dev_env_use_rhel7_artifacts|bool

    - include: roles/image-build/tasks/convert-qcow2-to-box.yml
      vars:
        image_build_name: rhel-7
        image_build_box: "{{ images_build_images['rhel-7'].box }}"
      when: dev_env_use_rhel7_artifacts|bool

    - include: roles/image-build/tasks/build-packer-qcow2.yml
      vars:
        image_build_iso: "{{ sles12_iso }}"
        image_build_name: sles-12
        image_build_disk_size: 4120
      when: dev_env_use_sles12_artifacts|bool

    - include: roles/image-build/tasks/convert-qcow2-to-box.yml
      vars:
        image_build_name: sles-12
        image_build_box: "{{ images_build_images['sles-12'].box }}"
      when: dev_env_use_sles12_artifacts|bool
