#
# (c) Copyright 2019 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Tasks for retrieving a Cirros qcow2 image via the Ardana qcow2 cache.
---

- name: tarballs-get-qcow2 | get-cirros-qcow2 | Determine Cirros qcow2 to download
  set_fact:
    _cirros_qcow2: "{{ cirros.artifacts.images[cirros_version] }}"

- name: tarballs-get-qcow2 | get-cirros-qcow2 | Get the Cirros qcow2
  include: "{{ playbook_dir }}/roles/ardana-cache/tasks/get-cached-file.yml"
  vars:
    _file:
      name: "{{ _cirros_qcow2.name }}.img"
      sha256: "{{ _cirros_qcow2.sha256 | default('') }}"
      url_path: "{{ tarballs_qcow2.base_url}}/{{ _cirros_qcow2.path }}"
      sha256url: "{{ tarballs_qcow2.base_url}}/{{ _cirros_qcow2.path
                  }}/{{ _cirros_qcow2.name }}.img.sha256"
      dir: "{{ tarballs_qcow2.qcow2_dir }}"
      link:
        name: "{{ _cirros_qcow2.link | default('') }}"
        dir: "{{ tarballs_qcow2.images_dir }}"
      use_proxy: "{{ tarballs_qcow2.use_proxy }}"
