# -*- mode: ruby -*-
# vi: set ft=ruby :

require File.expand_path(File.dirname(__FILE__)) + "/../lib/ardana_vagrant_helper.rb"

Vagrant.configure("2") do |config|
  ardana = Ardana::Config.new config
  ardana.set_ssh_config

  # Provider-specific settings
  ardana.set_provider_config

  ardana.set_vm_config

  # Server Definitions
  ardana.add_build

end
