#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Variables for the vagrant environment
---
vagrant_version: "1.7.2"
vagrant_plugin_install_version: "{{ lookup('env', 'ARDANA_VAGRANT_VERSION') | default('1.7.4', true) }}"

vagrant_plugins_remove:
  - fog-libvirt

vagrant_plugins_default:
  rack:
    version: "1.6.4"
    order: 1
  vagrant-openstack-plugin:
    version: "0.11.1"
    order: 2
  vagrant-libvirt:
    version: "0.0.35.hp.2"
    gem: "{{ dev_env_working_dir }}/ansible/roles/vagrant/files/vagrant-libvirt-0.0.35.hp.2.gem"
    order: 3
  vagrant-proxyconf:
    version: "1.5.0"
    order: 4
  fog:
    version: "1.29.0"
    order: 5

vagrant_plugins: "{{ vagrant_plugins_default |
                     update(vagrant_plugins_update |
                            default({})) }}"
vagrant_apt_packages:
  # required for vagrant plugins to build extensions
  - build-essential
  # required by ruby gems for building extensions with correct flags
  - pkg-config
  # required by ruby-libvirt gem to build extension against libvirt
  - libvirt-dev

vagrant_zypp_packages:
  # required by ruby gems for building extensions with correct flags
  - pkg-config
