#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Tasks to setup package repos for remote access on nodes other than the
# deployer.
---

- name: vagrant-cloud-setup | setup-remote-repos | Check for deployer ISO mounted repos
  delegate_to: "{{ deployer_node }}"
  stat:
    path: "{{ clmsetup.server.base }}/{{ clmsetup.distros[item.distro].dir }}/{{ item.path }}"
  with_items: clmsetup.isos
  register: _iso_mounted_result
  when:
    - item.enabled | bool

- name: vagrant-cloud-setup | setup-remote-repos | Setup remote ISO based repos (SUSE)
  become: yes
  shell: |
    set -eu

    if ! zypper repos "{{ item.item.alias }}"; then
      zypper addrepo \
          --type yast2 \
          --no-check \
          --no-keep-packages \
          --no-gpgcheck \
          --refresh \
          --name "{{ item.item.name }}" \
          "http://{{ deployer_address }}:79/{{ clmsetup.distros[item.item.distro].dir }}/{{ item.item.path }}" \
          "{{ item.item.alias }}"
          exit 55  # arbitrary exit code not generated by zypper as per man page
    fi
  register: _iso_repos_add_sles_result
  with_items: _iso_mounted_result.results
  when:
    - not (item | skipped)
    - ardana_family == "suse"
    - item.item.distro == ardana_distro
    - item.stat.exists
  changed_when:
    - _iso_repos_add_sles_result.rc == 55
  failed_when:
    - _iso_repos_add_sles_result.rc not in [0, 55]

- name: vagrant-cloud-setup | setup-remote-repos | Setup remote ISO based repos (RHEL)
  become: yes
  template:
    src: rhel.repo.j2
    dest: "/etc/yum.repos.d/{{ item.item.alias }}.repo"
  register: _iso_repos_add_rhel_result
  with_items: _iso_mounted_result.results
  when:
    - not (item | skipped)
    - ardana_family == "redhat"
    - item.item.distro == ardana_distro
    - item.stat.exists
  tags:
    - rhel

- name: vagrant-cloud-setup | setup-remote-repos | Check for deployer local directory repos
  delegate_to: "{{ deployer_node }}"
  stat:
    path: "{{ clmsetup.server.base }}/{{ clmsetup.distros[item.distro].dir }}/{{ item.path }}"
  with_items: clmsetup.repos
  register: _dir_repos_result
  when:
    - item.enabled | bool
    - item.mirror is defined

- name: vagrant-cloud-setup | setup-remote-repos | Setup remote directory based repos (SLES)
  become: yes
  shell: |
    set -eu

    if ! zypper repos "{{ item.item.alias }}"; then
      zypper addrepo \
          --no-check \
          --no-keep-packages \
          --no-gpgcheck \
          --refresh \
          --name "{{ item.item.name }}" \
          "http://{{ deployer_address }}:79/{{ clmsetup.distros[item.item.distro].dir }}/{{ item.item.path }}" \
          "{{ item.item.alias }}"
          exit 55  # arbitrary exit code not generated by zypper as per man page
    fi
  register: _dir_repos_add_sles_result
  with_items: _dir_repos_result.results
  when:
    - not (item | skipped)
    - ardana_family == "suse"
    - item.item.distro == ardana_distro
    - item.stat.exists
  changed_when:
    - _dir_repos_add_sles_result.rc == 55
  failed_when:
    - _dir_repos_add_sles_result.rc not in [0, 55]

- name: vagrant-cloud-setup | setup-remote-repos | Setup remote directory based repos (RHEL)
  become: yes
  template:
    src: rhel.repo.j2
    dest: "/etc/yum.repos.d/{{ item.item.alias }}.repo"
  register: _dir_repos_add_rhel_result
  with_items: _dir_repos_result.results
  when:
    - not (item | skipped)
    - ardana_family == "redhat"
    - item.item.distro == ardana_distro
    - item.stat.exists
  tags:
    - rhel

- name: vagrant-cloud-setup | setup-remote-repos | Check for deployer override repos
  delegate_to: "{{ deployer_node }}"
  stat:
    path: "{{ clmsetup.server.base }}/{{ clmsetup.distros[item.distro].dir }}/{{ item.path }}"
  with_items: clmsetup.repos
  register: _override_repos_result
  when:
    - item.enabled | bool
    - item.override is defined

- name: vagrant-cloud-setup | setup-remote-repos | Setup remote override repos (SLES)
  become: yes
  shell: |
    set -eu

    if ! zypper repos "{{ item.item.alias }}"; then
      zypper addrepo \
          --no-check \
          --no-keep-packages \
          --no-gpgcheck \
          --refresh \
          --priority "{{ item.item.priority | default(0) }}" \
          --name "{{ item.item.name }}" \
          "http://{{ deployer_address }}:79/{{ clmsetup.distros[item.item.distro].dir }}/{{ item.item.path }}" \
          "{{ item.item.alias }}"
          exit 55  # arbitrary exit code not generated by zypper as per man page
    fi
  register: _override_repos_add_sles_result
  with_items: _override_repos_result.results
  when:
    - not (item | skipped)
    - ardana_family == "suse"
    - item.item.distro == ardana_distro
    - item.stat.exists
  changed_when:
    - _override_repos_add_sles_result.rc == 55
  failed_when:
    - _override_repos_add_sles_result.rc not in [0, 55]

- name: vagrant-cloud-setup | setup-remote-repos | Setup remote override repos (RHEL)
  become: yes
  template:
    src: rhel.repo.j2
    dest: "/etc/yum.repos.d/{{ item.item.alias }}.repo"
  register: _override_repos_add_rhel_result
  with_items: _override_repos_result.results
  when:
    - not (item | skipped)
    - ardana_family == "redhat"
    - item.item.distro == ardana_distro
    - item.stat.exists
  tags:
    - rhel

- include: _refresh-repos.yml
  when:
    - ((_iso_repos_add_sles_result | changed) or (_iso_repos_add_rhel_result | changed) or
       (_dir_repos_add_sles_result | changed) or (_dir_repos_add_rhel_result | changed) or
       (_override_repos_add_sles_result | changed) or (_override_repos_add_rhel_result | changed))
