#
# (c) Copyright 2015-2017 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017-2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Site-specific servers
---
sites_default:
  provo:
    # proxy: host: web-proxy.example.com
    pip:
      host: bandersnatch.suse.provo.cloud
      port:
      prefix:
    apt:
      host: apt.suse.provo.cloud
      port:
    artefact:
      host: tarballs.suse.provo.cloud
      port:
      use_proxy: no
    ardana_artifacts_host: http://ardana.suse.provo.cloud
    ibs:
      #host: ibs-mirror.prv.suse.net
      host: 10.84.2.50
      path: ibs
      use_proxy: no
    clouddata:
      #host: provo-clouddata.cloud.suse.de
      host: 10.86.33.251
      use_proxy: no
    git:
      host: git.suse.provo.cloud

sites: "{{ sites_default | update(sites_update | default({})) }}"
